version: 0.0
Resources:
  - TargetService:
      Type: AWS::Lambda::Function
      Properties:
        Name: "podinfo-lambda"
        Alias: "live"
        CurrentVersion: "1"
        TargetVersion: "2"
